server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER:http://localhost:8080/realms/enterprise-lab}
          audiences: ticket-api
